In [1]:
import numpy as np

In [9]:
arr2 = np.array(([3,7.9,'a'] ,[5,6,1]))


print(arr2)
print(arr2.ndim)
print(arr2.shape)
print(arr2.size)
print(arr2.dtype)
print(arr2.itemsize)



[['3' '7.9' 'a']
 ['5' '6' '1']]
2
(2, 3)
6
<U32
128


In [ ]:
z = np.zeros([3,3]) 
z



array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
o = np.ones([2,3], dtype=int)
o

array([[1, 1, 1],
       [1, 1, 1]])

In [19]:
e = np.eye(3,3)


e

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
arr3= np.arange(0,12)
print(arr3)
arr3.reshape(3,4)
print(arr3)



[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [25]:
arr4 = np.linspace(0,1,10)
arr4

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [ ]:
arr5 = np.random.random(10)
arr5

array([0.73352763, 0.03230652, 0.04755427, 0.29775164, 0.36573863,
       0.32125479, 0.49620328, 0.98402917, 0.92775587, 0.31278588])

In [29]:
arr6= np.array([[-7,0,10,20],[-5,1,40,200],[-1,1,4,30]])
arr6


array([[ -7,   0,  10,  20],
       [ -5,   1,  40, 200],
       [ -1,   1,   4,  30]])

In [37]:
print(arr6[2,0:])

print(arr6[0:,2:3])



[-1  1  4 30]
[[10]
 [40]
 [ 4]]


In [38]:
arr6[1:,0:2]


array([[-5,  1],
       [-1,  1]])

In [39]:
for i in arr6.flat:
    print(i)

-7
0
10
20
-5
1
40
200
-1
1
4
30


In [42]:
a = np.arange(10,19).reshape((3,3))

np.apply_along_axis(np.max, axis=1, arr=a)

array([12, 15, 18])

In [43]:
b = np.random.random((3,3))
b


array([[0.98574717, 0.82109594, 0.59455902],
       [0.7413719 , 0.96618313, 0.85348881],
       [0.37242231, 0.69402521, 0.84160785]])

In [46]:
print(b>0.5)

print(b[b>0])

[[ True  True  True]
 [ True  True  True]
 [False  True  True]]
[0.98574717 0.82109594 0.59455902 0.7413719  0.96618313 0.85348881
 0.37242231 0.69402521 0.84160785]
