In [1]:
import numpy as np, pandas as pd, matplotlib.pyplot as plt
import matplotlib
import seaborn as sns
from scipy.stats import norm



###Question 1

In [5]:
#a
# i

zeros = np.zeros((3,4), dtype=np.int16)
zeros

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)

In [7]:
#ii

ones = np.ones((2,3),dtype=np.int16)
ones

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [10]:
random_vals = np.random.randint(0,10,(4,4),dtype=np.int16)
random_vals

array([[5, 5, 4, 9],
       [9, 4, 7, 1],
       [5, 9, 0, 3],
       [2, 5, 9, 6]], dtype=int16)

In [ ]:
new_random_vals = 